### ISSUE TITLE
Set-ShlinkUrl in combine with Get-ShlinkUrl

### ISSUE THREAD

**Issue by mariondj** [codaamok/PSShlink#4]
The call
Get-ShlinkUrl -SearchTerm "test" | Set-ShlinkUrl -ValidSince (Get-Date "2021-02-08") -ValidUntil (Get-Date "2021-02-13")
don't work correctly.
Set-ShlinkUrl whant the parameter LongUrl

**Comment by codaamok** [comment]
Thanks for raising. I will resolve soon.
