### ISSUE TITLE
Highlight PSShlink in shlink.io

### ISSUE THREAD

**Issue by acelaya** [codaamok/PSShlink#5]
Hey!

I see this is a pretty active project, and you keep it up to date with new Shlink versions.

Would you like PSShlink to be highlighted in the [Shlink Apps landing page](https://shlink.io/apps/)?

**Comment by codaamok** [comment]
That would be awesome - yes please! More users of the module will keep the wheels turning 😅

**Comment by acelaya** [comment]
Perfect. Will get it added then 🙂

**Comment by acelaya** [comment]
This is how it is looking so far:

![image](https://user-images.githubusercontent.com/2719332/142754797-0d8f52c6-be27-4b04-ae5f-16173fba68c3.png)

Considerations:

* I took the image from your blog, https://adamcook.io/p/using-powershell-to-manage-shlink-with-psshlink/, but I'll probably try to get another one with a bit more quality. If you can provide one, that's also perfect 🙂 
* The link with your name points to your website, https://adamcook.io/. Do you want me to point it somewhere else?
* Would you like to make any change in the general text? Some feature you would like to highlight?

**Comment by codaamok** [comment]
![image](https://user-images.githubusercontent.com/6683266/142767703-d07dc130-773e-40f6-ba95-cf3faf94d6c6.png)

How's this image?

> The link with your name points to your website, https://adamcook.io/. Do you want me to point it somewhere else?

How about to my Twitter handle? https://twitter.com/codaamok

> Would you like to make any change in the general text? Some feature you would like to highlight?

No I think that text is perfect. Short and clear.

**Comment by acelaya** [comment]
Done 🙂 https://shlink.io/apps/
